### ISSUE TITLE
Ability to stream audio source

### ISSUE THREAD

**Issue by swaggerwocky** [Mayerch1/TheDiscordSoundboard#13]
Could you add the ability to stream from an audio source, such as a virtual audio cable?

**Comment by Mayerch1** [comment]
I can look if the following implementation is possible with the currenly used libraries.

- You can select an input device from a list of all active devices
- After selection, the bot will start to stream the input of this device (e.g. audio cable, "What you hear", …)
- The stream should not be buffered into a file in order to prevent high latency above several hundred ms

**Comment by Mayerch1** [comment]
The feature is implemented. It just needs to get an usable ui before it can be realeased.

At the moment, your device needs to have 2 Channels @ 48000Hz (Discord default). I'll see if I can get other channels and sample rates to work.

**Comment by swaggerwocky** [comment]
Sounds great!

**Comment by Mayerch1** [comment]
#14 Merged into Master and Released
